### ISSUE TITLE
Operations returns an OpBinding value regardless of whether all operand is literal or not

### ISSUE THREAD

**Issue by Soya-Onishi** [chipsalliance/chisel3#1007]
**Type of issue**: feature request

**Impact**: unknown

**Development Phase**: request

 

**If the current behavior is a bug, please provide the steps to reproduce the problem:**

**What is the current behavior?**
For now, operations always return OpBinding value regardless of whether all operands are literal or not.
Probably, this behavior sometimes causes inconvenient.
For example, `is` in `switch` statement only accepts literal, and this is why the following is illegal.
```
switch(x) {
  is(Cat(1.U(2.W), 0.U(2.W))) { ... }
  ...
}
```
However, in C, this is legal(e.g. case 1 + 2: ...), so users that expect switch behavior like C probably confuse by this illegalness.

**What is the expected behavior?**
I think it is better that an operation of literals returns an ElementLitBinding value insted of OpBinding one.
If the solution already exists, please teach me.

**Please tell us about your environment:**

  - chiselVersion: `3.1.+ (chisel-template)`
  - scalaVersion:`2.11.12`
  - OS: `macOS HighSierra 10.13.6` 

**What is the use case for changing the behavior?**

**Comment by ducky64** [comment]
I'm not sure what the solution should be, but let me provide a bit of context behind this antifeature:
- Switch arguments must be literal so they can be checked for mutual exclusivity
- We don't do literal propagation / evaluation in the Chisel frontend because it could lead to subtle differences in behavior with FIRRTL (and we've been bit by this a few times) - meaning that different code style could cause different results. Technically, this would be due to a bug in Chisel / FIRRTL, but it's a likely one given that both need to stay exactly in sync (the fundamental cause from a software engineering point of view is duplicated or non-DRY code). This is why 1.U + 2.U in Chisel does not produce 3.U, and instead leaves it up to FIRRTL (or beyond) to do literal evaluation and propagation.

Of course, there's a bunch of assumptions here so there may be creative solutions, eg delegate literal prop in Chisel to a FIRRTL library, or delay switch statement mutual exclusivity checking to FIRRTL, perhaps with a mutual exclusivity annotation. @azidar ?

**Comment by jackkoenig** [comment]
In order to keep the code more-or-less DRY while supporting more propagation in Chisel, we could construct FIRRTL nodes as we go* and leverage FIRRTL's own constant propagation.

*Since names are not yet known, we'd have to do it in some name agnostic way, I don't think it would be all that difficult though.

**Comment by grebe** [comment]
What is the error given if you try to do an `is()` if the argument doesn't have a literal binding? It might be a good candidate for a better error message, e.g. by following an opbinding back to its leaf nodes.

**Comment by Soya-Onishi** [comment]
```
switch(io.in) {
  is(Cat(0.U, 0.U)) { ... }
  is(Cat(0.U, 1.U)) { ... }
  is(Cat(1.U, 0.U)) { ... }
  is(Cat(1.U, 1.U)) { ... }
}
```
The above code causes the following error.
```
[error] java.lang.IllegalArgumentException: requirement failed: is conditions must be literals!
[error] 	at scala.Predef$.require(Predef.scala:224)
[error] 	at chisel3.util.SwitchContext$$anonfun$1.apply(Conditional.scala:31)
[error] 	at chisel3.util.SwitchContext$$anonfun$1.apply(Conditional.scala:30)
...
```
This error tell me the Cat result is exactly not literal.
