### ISSUE TITLE
chiselName is interacting poorly with ElaborationArtefacts and throws head of empty list error

### ISSUE THREAD

**Issue by ccelio** [chipsalliance/chisel3#811]
**Type of issue**: bug report 

**Other information**

* I have added toString methods to my Modules.
* Some of the Module toString methods invoke children Module toString methods
* printing out a Module toString method works fine
* Passing a Module's toString value to an an ElaborationArtefacts crashes Chisel, but only if a child Module uses the `chiselName` macro.
* The current work-around is to store children toString output to a String value and then build up the parent toString's output (see: https://github.com/ucb-bar/riscv-boom/pull/73#pullrequestreview-114181924).

The error dump
````bash
[info] [37.484] Done elaborating.
[error] (run-main-0) java.util.NoSuchElementException: head of empty list
[error] java.util.NoSuchElementException: head of empty list
[error] 	at scala.collection.immutable.Nil$.head(List.scala:420)
[error] 	at scala.collection.immutable.Nil$.head(List.scala:417)
[error] 	at scala.collection.mutable.Stack.top(Stack.scala:132)
[error] 	at chisel3.internal.naming.NamingStack.pop_return_context(Namer.scala:133)
[error] 	at boom.exu.Rob.toString(rob.scala:185)
[error] 	at boom.exu.BoomCore.toString(core.scala:236)
[error] 	at boom.common.BoomTileModuleImp$$anonfun$29.apply(tile.scala:158)
[error] 	at boom.common.BoomTileModuleImp$$anonfun$29.apply(tile.scala:158)
[error] 	at freechips.rocketchip.util.GeneratorApp$$anonfun$generateArtefacts$1.apply(GeneratorUtils.scala:126)
[error] 	at freechips.rocketchip.util.GeneratorApp$$anonfun$generateArtefacts$1.apply(GeneratorUtils.scala:125)
[error] 	at scala.collection.immutable.List.foreach(List.scala:381)
[error] 	at freechips.rocketchip.util.GeneratorApp$class.generateArtefacts(GeneratorUtils.scala:125)
[error] 	at boom.system.Generator$.generateArtefacts(Generator.scala:13)
[error] 	at boom.system.Generator$.delayedEndpoint$boom$system$Generator$1(Generator.scala:99)
[error] 	at boom.system.Generator$delayedInit$body.apply(Generator.scala:13)
[error] 	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:381)
[error] 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
[error] 	at scala.App$class.main(App.scala:76)
[error] 	at boom.system.Generator$.main(Generator.scala:13)
[error] 	at boom.system.Generator.main(Generator.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:483)
[error] 	at sbt.Run.invokeMain(Run.scala:93)
[error] 	at sbt.Run.run0(Run.scala:87)
[error] 	at sbt.Run.execute$1(Run.scala:65)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:77)
[error] 	at sbt.Run$$Lambda$2488/1026854088.apply$mcV$sp(Unknown Source)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error] 	at sbt.Run$.executeTrapExit(Run.scala:124)
[error] 	at sbt.Run.run(Run.scala:77)
[error] 	at sbt.Defaults$.$anonfun$bgRunMainTask$6(Defaults.scala:1147)
[error] 	at sbt.Defaults$.$anonfun$bgRunMainTask$6$adapted(Defaults.scala:1142)
[error] 	at sbt.Defaults$$$Lambda$2471/1237897467.apply(Unknown Source)
[error] 	at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
[error] 	at sbt.internal.BackgroundThreadPool$$Lambda$2478/428957127.apply$mcV$sp(Unknown Source)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at scala.util.Try$.apply(Try.scala:209)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 39 s, completed Apr 21, 2018 10:56:23 PM
make: *** [/home/eng/celio/work/boom-template/vsim/generated-src/boom.system.TestHarness.MegaBoomConfig.fir] Error 1
````

The line `at boom.exu.Rob.toString(rob.scala:185)` points to the `@chiselName` macro.

**If the current behavior is a bug, please provide the steps to reproduce the problem:**

````bash
git clone https://github.com/ccelio/boom-template.git
cd boom-template
./scripts/init-submodules.sh
cd boom; git checkout master; git pull; cd ..;
cd verisim
make
````

Then go into `boom-template/boom/src/main/scala/exu/core.scala` and change:

    236    + rob_str + "\n"

to

    236    + rob.toString + "\n"

The ElaborationArtefact itself is at (https://github.com/ucb-bar/riscv-boom/blob/master/src/main/scala/common/tile.scala#L156-L160).

Related: https://github.com/ucb-bar/riscv-boom/pull/73#pullrequestreview-114181924

**Comment by jackkoenig** [comment]
`chiselName` has been replaced by the compiler plugin naming.
